# Generated by Django 3.1.7 on 2021-04-24 20:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(999999999), django.core.validators.MaxValueValidator(1000000000)])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('website', models.URLField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('prefix', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=100)),
                ('subtitle', models.NullBooleanField()),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('cover_image', models.ImageField(null=True, upload_to='')),
                ('released_date', models.DateField(blank=True, null=True)),
                ('review', models.TextField(max_length=1000)),
                ('ASIN', models.UUIDField()),
                ('directors', models.ManyToManyField(blank=True, null=True, to='Moviesapp.Director')),
                ('genre', models.ManyToManyField(blank=True, null=True, to='Moviesapp.Genre')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Moviesapp.studio')),
            ],
        ),
    ]
