# Generated by Django 3.1.7 on 2021-04-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='subtitle',
            field=models.BooleanField(null=True),
        ),
    ]
