# Generated by Django 3.1.7 on 2021-04-24 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moviesapp', '0002_auto_20210425_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='phone_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(999999999), django.core.validators.MaxValueValidator(100000000000)]),
        ),
    ]
