# Generated by Django 3.1.7 on 2021-04-25 16:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moviesapp', '0004_auto_20210425_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='review',
        ),
        migrations.AlterField(
            model_name='director',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='director',
            name='phone_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(100000000000)]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(height_field='50%', upload_to='Moviesapp/static/images', width_field='50%'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(to='Moviesapp.Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='Moviesapp.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='studio',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=1000)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moviesapp.movie')),
            ],
        ),
    ]
