# Generated by Django 3.1.7 on 2021-04-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moviesapp', '0005_auto_20210425_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ASIN',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='Moviesapp/static/images'),
        ),
    ]
